import type { Tool, Log, Request, SiteConfig } from '../types'

export const mockConfig: SiteConfig = {
  id: '1',
  hero_title: 'AI保险实验室',
  hero_subtitle: '100天，用AI做10个真实可用的保险小工具。从想法 → 开发 → 上线，全过程公开。',
  experiment_start_date: '2026-01-01',
}

export const mockTools: Tool[] = [
  {
    id: '1',
    number: 1,
    name: '医疗险推荐器',
    description: '输入年龄、预算、健康情况，AI帮你筛选最合适的医疗险产品',
    status: 'completed',
    start_date: '2026-01-01',
    complete_date: '2026-01-07',
    url: 'https://example.com/tool1',
    try_count: 128,
    vote_count: 0,
    features: '根据个人情况智能推荐\n对比多款产品差异\n生成推荐理由报告',
    how_to_use: '1. 填写基本信息\n2. 选择预算范围\n3. 查看推荐结果',
    notes: '已上线，新增百万医疗险对比功能',
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '2',
    number: 2,
    name: '保险条款解释工具',
    description: '粘贴晦涩的保险条款，AI用大白话帮你解释清楚',
    status: 'completed',
    start_date: '2026-01-08',
    complete_date: '2026-01-15',
    url: 'https://example.com/tool2',
    try_count: 89,
    vote_count: 0,
    features: '支持粘贴任意保险条款\n生成通俗易懂的解释\n标注重要风险点',
    how_to_use: '1. 粘贴条款文字\n2. 点击解释\n3. 查看通俗版本',
    notes: '优化了免责条款的解读准确率',
    created_at: '2026-01-08T00:00:00Z',
  },
  {
    id: '3',
    number: 3,
    name: '理赔材料清单生成器',
    description: '描述你的理赔情况，AI帮你生成需要准备的完整材料清单',
    status: 'developing',
    start_date: '2026-01-16',
    complete_date: null,
    url: null,
    try_count: 0,
    vote_count: 0,
    features: null,
    how_to_use: null,
    notes: '正在完成车险/医疗险/重疾险三类场景的智能匹配',
    created_at: '2026-01-16T00:00:00Z',
  },
  {
    id: '4',
    number: 4,
    name: '保费计算器',
    description: '快速估算各类险种的大致保费区间',
    status: 'upcoming',
    start_date: null,
    complete_date: null,
    url: null,
    try_count: 0,
    vote_count: 32,
    features: null,
    how_to_use: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '5',
    number: 5,
    name: '培训课件生成器',
    description: '输入险种知识点，AI自动生成结构化培训课件',
    status: 'upcoming',
    start_date: null,
    complete_date: null,
    url: null,
    try_count: 0,
    vote_count: 28,
    features: null,
    how_to_use: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
  },
  {
    id: '6',
    number: 6,
    name: '保险方案对比工具',
    description: '上传多份保险方案，AI帮你对比分析优劣势',
    status: 'upcoming',
    start_date: null,
    complete_date: null,
    url: null,
    try_count: 0,
    vote_count: 19,
    features: null,
    how_to_use: null,
    notes: null,
    created_at: '2026-01-01T00:00:00Z',
  },
]

export const mockLogs: Log[] = [
  {
    id: '1',
    tool_id: '3',
    date: '2026-01-20',
    title: 'Day 20：理赔材料清单生成器开发中',
    content: '今天完成了基础的理赔场景分类，梳理了车险、医疗险、重疾险三类主要理赔场景的材料清单。明天开始接入AI进行智能匹配。',
    type: 'daily',
    created_at: '2026-01-20T00:00:00Z',
  },
  {
    id: '2',
    tool_id: null,
    date: '2026-01-14',
    title: '第二周复盘：条款解释工具上线，用户反馈超预期',
    content: '本周完成了保险条款解释工具的开发和上线。收到了23条用户反馈，90%以上表示"比自己看懂容易多了"。发现一个问题：对于格外复杂的免责条款，AI解释有时过于简化，需要改进。',
    type: 'weekly',
    created_at: '2026-01-14T00:00:00Z',
  },
  {
    id: '3',
    tool_id: '1',
    date: '2026-01-07',
    title: 'Day 7：医疗险推荐器正式上线',
    content: '第一个工具正式上线！用了整整7天，从产品设计到开发测试全部完成。虽然功能还比较基础，但Happy Path已经完全可用了。',
    type: 'daily',
    created_at: '2026-01-07T00:00:00Z',
  },
]

export const mockRequests: Request[] = [
  {
    id: '1',
    problem: '我是保险代理人，每次给客户出方案都要手动对比好几款产品，非常耗时',
    current_solution: '用Excel表格手动整理对比，大概要花2-3小时',
    willing_to_try: '非常愿意，如果能省下这些时间太好了',
    nickname: '小张代理',
    contact: null,
    vote_count: 45,
    is_featured: true,
    status: '考虑中',
    created_at: '2026-01-15T00:00:00Z',
  },
  {
    id: '2',
    problem: '买了保险不知道自己到底保了什么，出险了也不知道该怎么理赔',
    current_solution: '只能打客服电话，每次要等很久',
    willing_to_try: '愿意',
    nickname: null,
    contact: null,
    vote_count: 31,
    is_featured: true,
    status: '待评估',
    created_at: '2026-01-18T00:00:00Z',
  },
  {
    id: '3',
    problem: '公司需要给员工做保险知识培训，但是内容枯燥，员工听不进去',
    current_solution: '买了一些培训课程，效果一般',
    willing_to_try: '如果能自动生成有趣的课件就太好了',
    nickname: '培训主管李',
    contact: 'wechat: xxxxx',
    vote_count: 18,
    is_featured: false,
    status: '待评估',
    created_at: '2026-01-19T00:00:00Z',
  },
]
